### ISSUE TITLE
runtime error when kubernetes service endpoints list is empty

### ISSUE THREAD

**Issue by justinclayton** [matt-deboer/mpp#5]
```panic: runtime error: index out of range
goroutine 1 [running]:
github.com/matt-deboer/mpp/pkg/locator/kuberneteslocator.(*kubeLocator).Endpoints(0xc4202daa00, 0xc420317920, 0x3, 0xc420212920, 0x0, 0x3)
	/home/travis/gopath/src/github.com/matt-deboer/mpp/pkg/locator/kuberneteslocator/kubernetes.go:68 +0x5f9
github.com/matt-deboer/mpp/pkg/selector.(*Selector).Select(0xc4202dfc80, 0x1673b90, 0xc420108738, 0x1)
	/home/travis/gopath/src/github.com/matt-deboer/mpp/pkg/selector/selector.go:51 +0x115
github.com/matt-deboer/mpp/pkg/router.(*Router).doSelection(0xc4201086c0)
	/home/travis/gopath/src/github.com/matt-deboer/mpp/pkg/router/router.go:106 +0xd0
github.com/matt-deboer/mpp/pkg/router.NewRouter(0x2540be400, 0xc42038a882, 0x1, 0x2, 0xc42038a890, 0x1, 0x1, 0xc42038a8c0, 0x1, 0x1, ...)
	/home/travis/gopath/src/github.com/matt-deboer/mpp/pkg/router/router.go:72 +0x247
main.main.func1(0xc4201883c0)
	/home/travis/gopath/src/github.com/matt-deboer/mpp/pkg/server/main.go:138 +0x21c
github.com/matt-deboer/mpp/vendor/github.com/urfave/cli.HandleAction(0x13e2aa0, 0x16732c8, 0xc4201883c0, 0xc42006a3c0, 0x0)
	/home/travis/gopath/src/github.com/matt-deboer/mpp/vendor/github.com/urfave/cli/app.go:487 +0x7c
github.com/matt-deboer/mpp/vendor/github.com/urfave/cli.(*App).Run(0xc420110d00, 0xc42000e1c0, 0x1, 0x1, 0x0, 0x0)
	/home/travis/gopath/src/github.com/matt-deboer/mpp/vendor/github.com/urfave/cli/app.go:259 +0x70d
main.main()
	/home/travis/gopath/src/github.com/matt-deboer/mpp/pkg/server/main.go:150 +0xd69
```

**Comment by matt-deboer** [comment]
Should be resolved in `v0.2.1`
